#!/bin/bash

echo "🔧 Twilio Configuration Update Script"
echo "====================================="
echo ""

echo "📋 Current Status:"
echo "✅ Account: Active (Trial with $15.15 balance)"
echo "✅ Admin phones: All configured and valid"
echo "⚠️  Phone number: Need to purchase for SMS"
echo "⚠️  WhatsApp: Need to configure sandbox"
echo ""

echo "📝 Required Actions:"
echo ""

echo "1. 🛒 Purchase Twilio Phone Number:"
echo "   - Go to: https://console.twilio.com/us1/develop/phone-numbers/manage/search"
echo "   - Search for numbers in India (+91) or US (+1)"
echo "   - Choose a number with SMS capability"
echo "   - After purchase, add to .env file:"
echo "     TWILIO_PHONE_NUMBER=+1234567890"
echo ""

echo "2. 📲 Configure WhatsApp Sandbox:"
echo "   - Go to: https://console.twilio.com/us1/develop/sms/try-it-out/whatsapp-learn"
echo "   - Find your sandbox keyword (e.g., 'join abc-def')"
echo "   - From EACH admin phone (+918017362522, +917029466263, +919433559980):"
echo "     Send: 'join your-keyword' to +14155238886"
echo "   - Add to .env file:"
echo "     TWILIO_WHATSAPP_NUMBER=+14155238886"
echo ""

echo "3. 🧪 Test Configuration:"
echo "   After completing steps 1 & 2, run:"
echo "   node test-notifications-fixed.js"
echo ""

echo "💡 Quick .env Updates Needed:"
echo "Add these lines to your .env file after purchasing phone number:"
echo ""
echo "# Add after purchasing phone number"
echo "TWILIO_PHONE_NUMBER=+your_purchased_number"
echo ""
echo "# Add for WhatsApp (sandbox number)"
echo "TWILIO_WHATSAPP_NUMBER=+14155238886"
echo ""

echo "🚀 Once configured, your notifications will work with:"
echo "✅ Email notifications (if Gmail App Password is set)"
echo "✅ SMS notifications (after phone number purchase)"
echo "✅ WhatsApp notifications (after sandbox setup)"
echo ""

echo "❓ Need help? Run: node configure-new-twilio.js"
